# Generated by Django 5.0.4 on 2024-04-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="mobile_phone_no",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
